[2018-07-16 17:09:43,340] ERROR {com.zaxxer.hikari.pool.HikariPool} - HikariPool-1 - Exception during pool initialization. 
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.ballerinalang.database.sql.SQLDatasource.buildDataSource(SQLDatasource.java:200)
	at org.ballerinalang.database.sql.SQLDatasource.init(SQLDatasource.java:65)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.createSQLDataSource(SQLDatasourceUtils.java:1222)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.createServerBasedDBClient(SQLDatasourceUtils.java:1150)
	at org.ballerinalang.database.mysql.CreateClient.execute(CreateClient.java:61)
	at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
	at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:389)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:260)
	at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:411)
	at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:153)
	at org.ballerinalang.bre.bvm.BLangScheduler.executeNow(BLangScheduler.java:81)
	at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:320)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:267)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:247)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunction(BLangFunctions.java:467)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunctions(BLangFunctions.java:138)
	at org.ballerinalang.util.program.BLangFunctions.invokeEntrypointCallable(BLangFunctions.java:110)
	at org.ballerinalang.BLangProgramRunner.runMain(BLangProgramRunner.java:70)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:124)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:117)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
 
[2018-07-16 17:14:33,152] ERROR {org.ballerinalang.launcher.Main} - Do you mean to run the ballerina package as a project? If so run ballerina init to make it a project with a .ballerina directory 
org.ballerinalang.util.exceptions.BallerinaException: Do you mean to run the ballerina package as a project? If so run ballerina init to make it a project with a .ballerina directory
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:90)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
 
